backend:
  name: github
  repo: https://github.com/Artewiva/mexo
  branch: main # o master, a seconda del branch principale del tuo repo

media_folder: "immagini pubbliche" # Salva le immagini direttamente nella cartella che hai già nel progetto
public_folder: "/immagini pubbliche"

collections:
  - name: "contenuti"
    label: "Contenuti del Sito"
    files:
      - file: "fonte/App.tsx" # O il percorso del file principale/dati che vuoi modificare
        name: "home_content"
        label: "Testi Principali"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "text"}